cp /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.dna.toplevel.fa /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_genome.fa
samtools faidx /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_genome.fa
makeblastdb -in /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_genome.fa -dbtype nucl
cp /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.104.gtf /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf
bash -c " set -euxo pipefail; /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/gtf_to_exon_gene_records.pl /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf  | sort -k 1,1 -k4,4g -k5,5g | uniq  > /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf.mini.sortu " 
STAR --runThreadN 12 --runMode genomeGenerate --genomeDir /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_genome.fa.star.idx   --genomeFastaFiles /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.dna.toplevel.fa  --limitGenomeGenerateRAM 40419136213  --limitSjdbInsertNsj 10000000  --genomeChrBinNbits 16  --sjdbGTFfile /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.104.gtf  --sjdbOverhang 150 
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/gtf_to_gene_spans.pl /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf > /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf.gene_spans
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/gtf_file_to_feature_seqs.pl --gtf_file /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf --genome_fa /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_genome.fa --seqType CDSplus > ref_annot.cdsplus.fa
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/dfam_repeat_masker.pl --dfam_hmm homo_sapiens_dfam.hmm --target_fa ref_annot.cdsplus.fa --out_masked ref_annot.cdsplus.dfam_masked.fa --CPU 12
cp ref_annot.cdsplus.dfam_masked.fa /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.cdsplus.fa
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/index_cdna_seqs.pl /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.cdsplus.fa
makeblastdb -in ref_annot.cdsplus.dfam_masked.fa -dbtype nucl
blastn -query ref_annot.cdsplus.dfam_masked.fa -db ref_annot.cdsplus.dfam_masked.fa -max_target_seqs 10000 -outfmt 6 -evalue 1e-10 -num_threads 12 -dust no -lcase_masking > ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6
bash -c " set -euxo pipefail; /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/blast_outfmt6_replace_trans_id_w_gene_symbol.pl ref_annot.cdsplus.dfam_masked.fa ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6 | gzip > ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6.genesym.gz" 
bash -c " set -euxo pipefail; /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/blast_select_single_per_gene_pair.pl ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6.genesym.gz | gzip > ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6.genesym.best.gz" 
bash -c " set -euxo pipefail; /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/filter_overlapping_blast_hits.pl ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6.genesym.best.gz /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf.gene_spans | gzip > ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6.genesym.best.overlaps_filt.gz" 
cp ref_annot.cdsplus.dfam_masked.fa.allvsall.outfmt6.genesym.best.overlaps_filt.gz /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/blast_pairs.dat.gz
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/index_blast_pairs.pl /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/blast_pairs.idx /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/blast_pairs.dat.gz
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/gtf_file_to_feature_seqs.pl --gtf_file /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.104.gtf --genome_fa /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.dna.toplevel.fa --seqType cDNA > ref_annot.cdna.fa
cp ref_annot.cdna.fa /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.cdna.fa
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/index_cdna_seqs.pl /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.cdna.fa
makeblastdb -in ref_annot.cdna.fa -dbtype nucl
blastn -query ref_annot.cdna.fa -db ref_annot.cdna.fa -max_target_seqs 10000 -outfmt 6 -evalue 1e-10 -num_threads 12 -dust no > ref_annot.cdna.fa.allvsall.outfmt6
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/isoform_blast_gene_chr_conversion.pl --blast_outfmt6 ref_annot.cdna.fa.allvsall.outfmt6 --gtf /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.104.gtf > ref_annot.cdna.fa.allvsall.outfmt6.toGenes
sort -k2,2 -k7,7 ref_annot.cdna.fa.allvsall.outfmt6.toGenes > ref_annot.cdna.fa.allvsall.outfmt6.toGenes.sorted
gzip -f ref_annot.cdna.fa.allvsall.outfmt6.toGenes.sorted
cp ref_annot.cdna.fa.allvsall.outfmt6.toGenes.sorted.gz /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/trans.blast.dat.gz
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/build_chr_gene_alignment_index.pl --blast_genes /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/trans.blast.dat.gz  --out_prefix /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/trans.blast.align_coords
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/build_prot_info_db.pl --gtf /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.104.gtf --genome_fa /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.dna.toplevel.fa --out_prefix /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot
cp /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/AnnotFilterRuleLib/AnnotFilterRule.pm /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/.
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/build_fusion_annot_db_index.pl --gene_spans /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/ref_annot.gtf.gene_spans --out_db_file /scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/ctat_genome_lib_build_dir/fusion_annot_lib.idx
/scratch/alpine/dyammons@colostate.edu/star-fusion/ctat-genome-lib-builder/util/gtf_file_to_feature_seqs.pl --gtf_file /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.104.gtf --genome_fa /projects/dyammons@colostate.edu/references/canine/Canis_lupus_familiaris.CanFam3.1.dna.toplevel.fa --seqType prot > ref_annot.pep.fa
hmmscan --cpu 4 --domtblout PFAM.domtblout.dat Pfam-A.hmm ref_annot.pep.fa
